version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=boadbprod
      - MYSQL_USER=boa_user
      - MYSQL_PASSWORD=boa_pass
    volumes:
      - /data/mysql
  boa-app:
    image: repo/kycprocess-compose-app
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
    ports:
      - 7888:6099
    volumes:
      - /data/compose-app